import dash_core_components as dcc
import dash_html_components as html


def create_layout():
    return html.Div(
        style={"display": "flex", "height": "100vh"},
        children=[
            # Left Panel (Text Input and Controls)
            html.Div(
                style={"width": "30%", "padding": "20px", "backgroundColor": "#f2f2f2"},
                children=[
                    html.H2("Airbnb Listing Finder"),
                    html.Hr(),
                    html.H4("Describe the listings you are looking for:"),
                    dcc.Textarea(
                        id="text-input",
                        placeholder="e.g., Find me a private room in Brooklyn.",
                        style={
                            "width": "100%",
                            "height": "150px",
                            "marginBottom": "10px",
                        },
                    ),
                    html.Button(
                        "Search Listings",
                        id="analyze-button",
                        n_clicks=0,
                        style={
                            "width": "100%",
                            "padding": "10px",
                            "backgroundColor": "#007BFF",
                            "color": "white",
                            "border": "none",
                            "borderRadius": "5px",
                            "cursor": "pointer",
                        },
                    ),
                    dcc.Loading(
                        id="loading-output",
                        type="default",
                        children=html.Div(
                            id="found-locations-output",
                            style={"marginTop": "20px", "fontWeight": "bold"},
                        ),
                    ),
                ],
            ),
            # Right Panel (Map)
            html.Div(
                style={"width": "70%"},
                children=[
                    html.Iframe(
                        id="folium-map-llm",
                        srcDoc=None,  # Map will be generated by callback
                        width="100%",
                        height="100%",
                    )
                ],
            ),
        ],
    )
